# Generated by Django 6.0.2 on 2026-02-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isthis_food',
            field=models.FloatField(default=0),
        ),
    ] 
